/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Restrained Modern Enterprise Palette
        primary: "#2563EB",            // Primary Blue
        "on-primary": "#ffffff",
        "primary-hover": "#1D4ED8",
        "primary-container": "#2563EB",
        "on-primary-container": "#ffffff",
        "primary-light": "#EFF6FF",
        "primary-fixed": "#DBEAFE",
        "primary-fixed-dim": "#BFDBFE",
        "on-primary-fixed": "#1E3A8A",
        "on-primary-fixed-variant": "#1D4ED8",
        "inverse-primary": "#93C5FD",

        navy: "#0F172A",               // Dark Navy
        "navy-light": "#1E293B",

        teal: {
          DEFAULT: "#14B8A6",          // Accent Teal
          50: "#F0FDFA",
          100: "#CCFBF1",
          500: "#14B8A6",
          600: "#0D9488",
          700: "#0F766E",
          800: "#115E59",
          900: "#134E4A",
        },

        secondary: "#475569",
        "on-secondary": "#ffffff",
        "secondary-container": "#F1F5F9",
        "on-secondary-container": "#334155",
        "secondary-fixed": "#E2E8F0",
        "secondary-fixed-dim": "#CBD5E1",
        "on-secondary-fixed": "#0F172A",
        "on-secondary-fixed-variant": "#334155",

        tertiary: "#0D9488",           // Teal accent
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0F766E",
        "on-tertiary-container": "#CCFBF1",
        "tertiary-fixed": "#CCFBF1",
        "tertiary-fixed-dim": "#5EEAD4",
        "on-tertiary-fixed": "#115E59",
        "on-tertiary-fixed-variant": "#134E4A",

        error: "#EF4444",
        "on-error": "#ffffff",
        "error-container": "#FEE2E2",
        "on-error-container": "#991B1B",

        // Clean subtle surfaces & neutrals
        surface: "#FFFFFF",
        "on-surface": "#0F172A",
        "surface-variant": "#F1F5F9",
        "on-surface-variant": "#475569",
        "surface-dim": "#E2E8F0",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F8FAFC",
        "surface-container": "#F1F5F9",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "surface-tint": "#2563EB",

        "inverse-surface": "#0F172A",
        "inverse-on-surface": "#F8FAFC",
        outline: "#94A3B8",
        "outline-variant": "#E2E8F0",
        background: "#F8FAFC",
        "on-background": "#0F172A",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "container-max": "80rem",
      },
      fontFamily: {
        sans: ["Inter", "Plus Jakarta Sans", "system-ui", "-apple-system", "sans-serif"],
        display: ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "display-mobile": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};